version: "3"
services:
    mongo:
        image: mongo
        restart: unless-stopped
        ports: 
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=test
    web:
        image: nginx
        volumes:
            - ./templates:/etc/nginx/templates
            - ../Users/melogo/Desktop/singglerr-gras_ui-8248dade1601/dist:/etc/nginx/dist
        ports:
            - "80:80"